version: '3'

services:
  app:
    build: api/
    environment:
      KASM_URL: https://127.0.0.1:8001
    ports:
      - 8080:8080
    networks:
      - app
  
  oidc:
    image: quay.io/oauth2-proxy/oauth2-proxy
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_PASS_HOST_HEADER: true
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
      OAUTH2_PROXY_CLIENT_ID: ${CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_COOKIE_SECURE: false
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: true
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER': true
      OAUTH2_PROXY_PASS_USER_HEADERS: true
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: true  # required to enabled ID token verification
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://login.microsoftonline.com/${TENANT_ID}/v2.0
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_REDIRECT_URL: https://localhost:8001/oauth2/callback
    networks:
      - app

  nginx:
    image: nginx
    ports:
      - "8001:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/
    networks:
      - app

  kasm:
    image: kasmweb/ubuntu-jammy-desktop:1.13.0
    shm_size: 512  # Reccomended 512 MB for /dev/shm
    environment:
      VNC_PW: password
    networks:
      - app

networks:
  app:
    driver: bridge
